# Directory where pulled OCI images will be stored
image_dir = "/usr/share/tedge/flows"

# Directory where deployment instance TOML files will be written
deploy_dir = '{{ .Env.TEDGE_CONFIG_DIR }}/mappers/{{ .Mapper }}/flows'

[[registries]]
registry = "ghcr.io"
username = ""
password = ""
